FROM panuwitp/mosquitto-arm

# The following container is using the standard Mosquitto service. We include the config if you need to make changes

# USER root
# COPY ./mosquitto.conf /mosquitto/config/mosquitto.conf
